<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.1500" tests="6" failures="3">
  <testsuite name="Root Suite" timestamp="2021-06-01T18:04:12" tests="0" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="order_processor" timestamp="2021-06-01T18:04:12" tests="6" file="D:\Learning\HackerRank&apos;s Certification Tests\node basic 2\test\index.spec.js" time="0.1500" failures="3">
    <testcase name="order_processor Should have all the method placeOrder in the class" time="0.0010" classname="Should have all the method placeOrder in the class">
    </testcase>
    <testcase name="order_processor Should emit the event PROCESSING_STARTED when placeOrder is called" time="0.0280" classname="Should emit the event PROCESSING_STARTED when placeOrder is called">
    </testcase>
    <testcase name="order_processor Should emit the PROCESSING_FAILED if line items are empty" time="0.0310" classname="Should emit the PROCESSING_FAILED if line items are empty">
    </testcase>
    <testcase name="order_processor Should emit the PROCESSING_FAILED if any of the line items do not meet the stock requirements" time="0.0310" classname="Should emit the PROCESSING_FAILED if any of the line items do not meet the stock requirements">
      <failure message="expected 2 to deeply equal 0" type="AssertionError"><![CDATA[AssertionError: expected 2 to deeply equal 0
    at Timeout._onTimeout (test\index.spec.js:88:39)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)]]></failure>
    </testcase>
    <testcase name="order_processor Should emit the PROCESSING_SUCCESS if all the validations pass" time="0.0290" classname="Should emit the PROCESSING_SUCCESS if all the validations pass">
      <failure message="expected 0 to deeply equal 1" type="AssertionError"><![CDATA[AssertionError: expected 0 to deeply equal 1
    at Timeout._onTimeout (test\index.spec.js:116:43)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)]]></failure>
    </testcase>
    <testcase name="order_processor Should emit the PROCESSING_SUCCESS if all the validations pass for multiple orders" time="0.0300" classname="Should emit the PROCESSING_SUCCESS if all the validations pass for multiple orders">
      <failure message="expected 0 to deeply equal 2" type="AssertionError"><![CDATA[AssertionError: expected 0 to deeply equal 2
    at Timeout._onTimeout (test\index.spec.js:155:43)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)]]></failure>
    </testcase>
  </testsuite>
</testsuites>